#*****************************************************************************************
# Vivado (TM) v2025.1 (64-bit)
#
# rebuild.tcl: Tcl script for re-creating project 'Mini_Project_Starter'
#
# Generated by Vivado on Mon Jul 21 14:24:30 -0400 2025
# IP Build 6138677 on Thu May 22 03:10:11 MDT 2025
#
# This file contains the Vivado Tcl commands for re-creating the project to the state*
# when this script was generated. In order to re-create the project, please source this
# file in the Vivado Tcl Shell.
#
# * Note that the runs in the created project will be configured the same way as the
#   original project, however they will not be launched automatically. To regenerate the
#   run results please launch the synthesis/implementation runs as needed.
#
#*****************************************************************************************
# NOTE: In order to use this script for source control purposes, please make sure that the
#       following files are added to the source control system:-
#
# 1. This project restoration tcl script (rebuild.tcl) that was generated.
#
# 2. The following source(s) files that were local or imported into the original project.
#    (Please see the '$orig_proj_dir' and '$origin_dir' variable setting below at the start of the script)
#
#    "C:/Projects/fpga_mini_project_starter/Mini_Project_Starter/Mini_Project_Starter.srcs/utils_1/imports/synth_1/Pong_720p_Top.dcp"
#
# 3. The following remote source files that were added to the original project:-
#
#    "C:/Projects/fpga_mini_project_starter/rtl/Font_ROM.sv"
#    "C:/Projects/fpga_mini_project_starter/rtl/RAM_Single_Port.sv"
#    "C:/Projects/fpga_mini_project_starter/rtl/ROM.sv"
#    "C:/Projects/fpga_mini_project_starter/rtl/TMDS_Encoder.sv"
#    "C:/Projects/fpga_mini_project_starter/rtl/TMDS_Serializer.sv"
#    "C:/Projects/fpga_mini_project_starter/rtl/TM_Choice.sv"
#    "C:/Projects/fpga_mini_project_starter/rtl/Text_Overlay.sv"
#    "C:/Projects/fpga_mini_project_starter/rtl/Video_Signal_Generator.sv"
#    "C:/Projects/fpga_mini_project_starter/rtl/Text_Overlay_720p_Top.sv"
#    "C:/Projects/fpga_mini_project_starter/rtl/RAM.sv"
#    "C:/Projects/fpga_mini_project_starter/rtl/Block_Sprite.sv"
#    "C:/Projects/fpga_mini_project_starter/rtl/Pong_720p.sv"
#    "C:/Projects/fpga_mini_project_starter/rtl/Pong_720p_Top.sv"
#    "C:/Projects/fpga_mini_project_starter/rtl/Test_Pattern_Generator.sv"
#    "C:/Projects/fpga_mini_project_starter/rtl/Test_Pattern_720p_Top.sv"
#    "C:/Projects/fpga_mini_project_starter/rtl/Square_Pattern_Hdmi_480p_Top.sv"
#    "C:/Projects/fpga_mini_project_starter/rtl/Square_Pattern_Hdmi_720p_Top.sv"
#    "C:/Projects/fpga_mini_project_starter/rtl/FIFO.sv"
#    "C:/Projects/fpga_mini_project_starter/rtl/Clock_Enable_Generator.vhd"
#    "C:/Projects/fpga_mini_project_starter/rtl/Binary_To_7Segment.vhd"
#    "C:/Projects/fpga_mini_project_starter/rtl/Counter_7Segment.vhd"
#    "C:/Projects/fpga_mini_project_starter/rtl/Blinking_Led.vhd"
#    "C:/Projects/fpga_mini_project_starter/rsc/VGA8.F16.mem"
#    "C:/Projects/fpga_mini_project_starter/rsc/Zero.RAM.mem"
#    "C:/Projects/fpga_mini_project_starter/ip/clk_wiz_720p_0/clk_wiz_720p_0.xci"
#    "C:/Projects/fpga_mini_project_starter/ip/clk_wiz_0/clk_wiz_0.xci"
#    "C:/Projects/fpga_mini_project_starter/cons/pynqz2_constraints.xdc"
#    "C:/Projects/fpga_mini_project_starter/cons/blinking_led_constraints.xdc"
#    "C:/Projects/fpga_mini_project_starter/cons/counter_7segment_constraints.xdc"
#    "C:/Projects/fpga_mini_project_starter/cons/hdmi_constraints.xdc"
#    "C:/Projects/fpga_mini_project_starter/cons/hdmi_720p_constraints.xdc"
#    "C:/Projects/fpga_mini_project_starter/cons/test_pattern_constraints.xdc"
#    "C:/Projects/fpga_mini_project_starter/cons/pong_720p_constraints.xdc"
#    "C:/Projects/fpga_mini_project_starter/cons/text_overlay_720p.xdc"
#    "C:/Projects/fpga_mini_project_starter/tb/Text_Overlay_TB.sv"
#    "C:/Projects/fpga_mini_project_starter/tb/Font_ROM_TB.sv"
#    "C:/Projects/fpga_mini_project_starter/tb/TM_Choice_TB.sv"
#    "C:/Projects/fpga_mini_project_starter/tb/ROM_TB.sv"
#    "C:/Projects/fpga_mini_project_starter/tb/RAM_TB.sv"
#    "C:/Projects/fpga_mini_project_starter/tb/Video_Signal_Generator_TB.sv"
#    "C:/Projects/fpga_mini_project_starter/tb/FIFO_TB.sv"
#    "C:/Projects/fpga_mini_project_starter/tb/Clock_TB.sv"
#    "C:/Projects/fpga_mini_project_starter/tb/Counter_7Segment_TB.vhd"
#    "C:/Projects/fpga_mini_project_starter/tb/Binary_To_7Segment_TB.vhd"
#    "C:/Projects/fpga_mini_project_starter/tb/Blinking_Led_TB.vhd"
#    "C:/Projects/fpga_mini_project_starter/rsc/VGA8_testing.F16.mem"
#
#*****************************************************************************************

# Check file required for this script exists
proc checkRequiredFiles { origin_dir} {
  set status true
  set files [list \
 "[file normalize "$origin_dir/Mini_Project_Starter/Mini_Project_Starter.srcs/utils_1/imports/synth_1/Pong_720p_Top.dcp"]"\
  ]
  foreach ifile $files {
    if { ![file isfile $ifile] } {
      puts " Could not find local file $ifile "
      set status false
    }
  }

  set files [list \
 "[file normalize "$origin_dir/rtl/Font_ROM.sv"]"\
 "[file normalize "$origin_dir/rtl/RAM_Single_Port.sv"]"\
 "[file normalize "$origin_dir/rtl/ROM.sv"]"\
 "[file normalize "$origin_dir/rtl/TMDS_Encoder.sv"]"\
 "[file normalize "$origin_dir/rtl/TMDS_Serializer.sv"]"\
 "[file normalize "$origin_dir/rtl/TM_Choice.sv"]"\
 "[file normalize "$origin_dir/rtl/Text_Overlay.sv"]"\
 "[file normalize "$origin_dir/rtl/Video_Signal_Generator.sv"]"\
 "[file normalize "$origin_dir/rtl/Text_Overlay_720p_Top.sv"]"\
 "[file normalize "$origin_dir/rtl/RAM.sv"]"\
 "[file normalize "$origin_dir/rtl/Block_Sprite.sv"]"\
 "[file normalize "$origin_dir/rtl/Pong_720p.sv"]"\
 "[file normalize "$origin_dir/rtl/Pong_720p_Top.sv"]"\
 "[file normalize "$origin_dir/rtl/Test_Pattern_Generator.sv"]"\
 "[file normalize "$origin_dir/rtl/Test_Pattern_720p_Top.sv"]"\
 "[file normalize "$origin_dir/rtl/Square_Pattern_Hdmi_480p_Top.sv"]"\
 "[file normalize "$origin_dir/rtl/Square_Pattern_Hdmi_720p_Top.sv"]"\
 "[file normalize "$origin_dir/rtl/FIFO.sv"]"\
 "[file normalize "$origin_dir/rtl/Clock_Enable_Generator.vhd"]"\
 "[file normalize "$origin_dir/rtl/Binary_To_7Segment.vhd"]"\
 "[file normalize "$origin_dir/rtl/Counter_7Segment.vhd"]"\
 "[file normalize "$origin_dir/rtl/Blinking_Led.vhd"]"\
 "[file normalize "$origin_dir/rsc/VGA8.F16.mem"]"\
 "[file normalize "$origin_dir/rsc/Zero.RAM.mem"]"\
 "[file normalize "$origin_dir/ip/clk_wiz_720p_0/clk_wiz_720p_0.xci"]"\
 "[file normalize "$origin_dir/ip/clk_wiz_0/clk_wiz_0.xci"]"\
 "[file normalize "$origin_dir/cons/pynqz2_constraints.xdc"]"\
 "[file normalize "$origin_dir/cons/blinking_led_constraints.xdc"]"\
 "[file normalize "$origin_dir/cons/counter_7segment_constraints.xdc"]"\
 "[file normalize "$origin_dir/cons/hdmi_constraints.xdc"]"\
 "[file normalize "$origin_dir/cons/hdmi_720p_constraints.xdc"]"\
 "[file normalize "$origin_dir/cons/test_pattern_constraints.xdc"]"\
 "[file normalize "$origin_dir/cons/pong_720p_constraints.xdc"]"\
 "[file normalize "$origin_dir/cons/text_overlay_720p.xdc"]"\
 "[file normalize "$origin_dir/tb/Text_Overlay_TB.sv"]"\
 "[file normalize "$origin_dir/tb/Font_ROM_TB.sv"]"\
 "[file normalize "$origin_dir/tb/TM_Choice_TB.sv"]"\
 "[file normalize "$origin_dir/tb/ROM_TB.sv"]"\
 "[file normalize "$origin_dir/tb/RAM_TB.sv"]"\
 "[file normalize "$origin_dir/tb/Video_Signal_Generator_TB.sv"]"\
 "[file normalize "$origin_dir/tb/FIFO_TB.sv"]"\
 "[file normalize "$origin_dir/tb/Clock_TB.sv"]"\
 "[file normalize "$origin_dir/tb/Counter_7Segment_TB.vhd"]"\
 "[file normalize "$origin_dir/tb/Binary_To_7Segment_TB.vhd"]"\
 "[file normalize "$origin_dir/tb/Blinking_Led_TB.vhd"]"\
 "[file normalize "$origin_dir/rsc/VGA8_testing.F16.mem"]"\
  ]
  foreach ifile $files {
    if { ![file isfile $ifile] } {
      puts " Could not find remote file $ifile "
      set status false
    }
  }

  return $status
}
# Set the reference directory for source file relative paths (by default the value is script directory path)
set origin_dir "."

# Use origin directory path location variable, if specified in the tcl shell
if { [info exists ::origin_dir_loc] } {
  set origin_dir $::origin_dir_loc
}

# Set the project name
set _xil_proj_name_ "Mini_Project_Starter"

# Use project name variable, if specified in the tcl shell
if { [info exists ::user_project_name] } {
  set _xil_proj_name_ $::user_project_name
}

variable script_file
set script_file "rebuild.tcl"

# Help information for this script
proc print_help {} {
  variable script_file
  puts "\nDescription:"
  puts "Recreate a Vivado project from this script. The created project will be"
  puts "functionally equivalent to the original project for which this script was"
  puts "generated. The script contains commands for creating a project, filesets,"
  puts "runs, adding/importing sources and setting properties on various objects.\n"
  puts "Syntax:"
  puts "$script_file"
  puts "$script_file -tclargs \[--origin_dir <path>\]"
  puts "$script_file -tclargs \[--project_name <name>\]"
  puts "$script_file -tclargs \[--help\]\n"
  puts "Usage:"
  puts "Name                   Description"
  puts "-------------------------------------------------------------------------"
  puts "\[--origin_dir <path>\]  Determine source file paths wrt this path. Default"
  puts "                       origin_dir path value is \".\", otherwise, the value"
  puts "                       that was set with the \"-paths_relative_to\" switch"
  puts "                       when this script was generated.\n"
  puts "\[--project_name <name>\] Create project with the specified name. Default"
  puts "                       name is the name of the project from where this"
  puts "                       script was generated.\n"
  puts "\[--help\]               Print help information for this script"
  puts "-------------------------------------------------------------------------\n"
  exit 0
}

if { $::argc > 0 } {
  for {set i 0} {$i < $::argc} {incr i} {
    set option [string trim [lindex $::argv $i]]
    switch -regexp -- $option {
      "--origin_dir"   { incr i; set origin_dir [lindex $::argv $i] }
      "--project_name" { incr i; set _xil_proj_name_ [lindex $::argv $i] }
      "--help"         { print_help }
      default {
        if { [regexp {^-} $option] } {
          puts "ERROR: Unknown option '$option' specified, please type '$script_file -tclargs --help' for usage info.\n"
          return 1
        }
      }
    }
  }
}

# Set the directory path for the original project from where this script was exported
set orig_proj_dir "[file normalize "$origin_dir/Mini_Project_Starter"]"

# Check for paths and files needed for project creation
set validate_required 0
if { $validate_required } {
  if { [checkRequiredFiles $origin_dir] } {
    puts "Tcl file $script_file is valid. All files required for project creation is accesable. "
  } else {
    puts "Tcl file $script_file is not valid. Not all files required for project creation is accesable. "
    return
  }
}

# Create project
create_project ${_xil_proj_name_} ./${_xil_proj_name_} -part xc7z020clg400-1

# Set the directory path for the new project
set proj_dir [get_property directory [current_project]]

# Reconstruct message rules
# None

# Set project properties
set obj [current_project]
set_property -name "board_part_repo_paths" -value "[file normalize "$origin_dir/../../Users/edeli/AppData/Roaming/Xilinx/Vivado/2024.2/xhub/board_store/xilinx_board_store"]" -objects $obj
set_property -name "board_part" -value "tul.com.tw:pynq-z2:part0:1.0" -objects $obj
set_property -name "customized_default_ip_location" -value "C:/WriteLockDummy" -objects $obj
set_property -name "default_lib" -value "xil_defaultlib" -objects $obj
set_property -name "enable_resource_estimation" -value "0" -objects $obj
set_property -name "enable_vhdl_2008" -value "1" -objects $obj
set_property -name "ip_cache_permissions" -value "read write" -objects $obj
set_property -name "ip_output_repo" -value "$proj_dir/${_xil_proj_name_}.cache/ip" -objects $obj
set_property -name "mem.enable_memory_map_generation" -value "1" -objects $obj
set_property -name "platform.board_id" -value "pynq-z2" -objects $obj
set_property -name "revised_directory_structure" -value "1" -objects $obj
set_property -name "sim.central_dir" -value "$proj_dir/${_xil_proj_name_}.ip_user_files" -objects $obj
set_property -name "sim.ip.auto_export_scripts" -value "1" -objects $obj
set_property -name "simulator_language" -value "Mixed" -objects $obj
set_property -name "sim_compile_state" -value "1" -objects $obj
set_property -name "use_inline_hdl_ip" -value "1" -objects $obj
set_property -name "webtalk.activehdl_export_sim" -value "10" -objects $obj
set_property -name "webtalk.modelsim_export_sim" -value "10" -objects $obj
set_property -name "webtalk.questa_export_sim" -value "10" -objects $obj
set_property -name "webtalk.riviera_export_sim" -value "10" -objects $obj
set_property -name "webtalk.xsim_export_sim" -value "10" -objects $obj
set_property -name "webtalk.xsim_launch_sim" -value "815" -objects $obj
set_property -name "xpm_libraries" -value "XPM_CDC" -objects $obj

# Create 'sources_1' fileset (if not found)
if {[string equal [get_filesets -quiet sources_1] ""]} {
  create_fileset -srcset sources_1
}

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 [file normalize "${origin_dir}/rtl/Font_ROM.sv"] \
 [file normalize "${origin_dir}/rtl/RAM_Single_Port.sv"] \
 [file normalize "${origin_dir}/rtl/ROM.sv"] \
 [file normalize "${origin_dir}/rtl/TMDS_Encoder.sv"] \
 [file normalize "${origin_dir}/rtl/TMDS_Serializer.sv"] \
 [file normalize "${origin_dir}/rtl/TM_Choice.sv"] \
 [file normalize "${origin_dir}/rtl/Text_Overlay.sv"] \
 [file normalize "${origin_dir}/rtl/Video_Signal_Generator.sv"] \
 [file normalize "${origin_dir}/rtl/Text_Overlay_720p_Top.sv"] \
 [file normalize "${origin_dir}/rtl/RAM.sv"] \
 [file normalize "${origin_dir}/rtl/Block_Sprite.sv"] \
 [file normalize "${origin_dir}/rtl/Pong_720p.sv"] \
 [file normalize "${origin_dir}/rtl/Pong_720p_Top.sv"] \
 [file normalize "${origin_dir}/rtl/Test_Pattern_Generator.sv"] \
 [file normalize "${origin_dir}/rtl/Test_Pattern_720p_Top.sv"] \
 [file normalize "${origin_dir}/rtl/Square_Pattern_Hdmi_480p_Top.sv"] \
 [file normalize "${origin_dir}/rtl/Square_Pattern_Hdmi_720p_Top.sv"] \
 [file normalize "${origin_dir}/rtl/FIFO.sv"] \
 [file normalize "${origin_dir}/rtl/Clock_Enable_Generator.vhd"] \
 [file normalize "${origin_dir}/rtl/Binary_To_7Segment.vhd"] \
 [file normalize "${origin_dir}/rtl/Counter_7Segment.vhd"] \
 [file normalize "${origin_dir}/rtl/Blinking_Led.vhd"] \
 [file normalize "${origin_dir}/rsc/VGA8.F16.mem"] \
 [file normalize "${origin_dir}/rsc/Zero.RAM.mem"] \
]
add_files -norecurse -fileset $obj $files

# Set 'sources_1' fileset file properties for remote files
set file "$origin_dir/rtl/Font_ROM.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/rtl/RAM_Single_Port.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/rtl/ROM.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/rtl/TMDS_Encoder.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj
set_property -name "used_in" -value "synthesis implementation" -objects $file_obj
set_property -name "used_in_simulation" -value "0" -objects $file_obj

set file "$origin_dir/rtl/TMDS_Serializer.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj
set_property -name "used_in" -value "synthesis implementation" -objects $file_obj
set_property -name "used_in_simulation" -value "0" -objects $file_obj

set file "$origin_dir/rtl/TM_Choice.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/rtl/Text_Overlay.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/rtl/Video_Signal_Generator.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/rtl/Text_Overlay_720p_Top.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj
set_property -name "used_in" -value "synthesis implementation" -objects $file_obj
set_property -name "used_in_simulation" -value "0" -objects $file_obj

set file "$origin_dir/rtl/RAM.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/rtl/Block_Sprite.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/rtl/Pong_720p.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/rtl/Pong_720p_Top.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj
set_property -name "used_in" -value "synthesis implementation" -objects $file_obj
set_property -name "used_in_simulation" -value "0" -objects $file_obj

set file "$origin_dir/rtl/Test_Pattern_Generator.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj
set_property -name "used_in" -value "synthesis implementation" -objects $file_obj
set_property -name "used_in_simulation" -value "0" -objects $file_obj

set file "$origin_dir/rtl/Test_Pattern_720p_Top.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj
set_property -name "used_in" -value "synthesis implementation" -objects $file_obj
set_property -name "used_in_simulation" -value "0" -objects $file_obj

set file "$origin_dir/rtl/Square_Pattern_Hdmi_480p_Top.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj
set_property -name "used_in" -value "synthesis implementation" -objects $file_obj
set_property -name "used_in_simulation" -value "0" -objects $file_obj

set file "$origin_dir/rtl/Square_Pattern_Hdmi_720p_Top.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj
set_property -name "used_in" -value "synthesis implementation" -objects $file_obj
set_property -name "used_in_simulation" -value "0" -objects $file_obj

set file "$origin_dir/rtl/FIFO.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/rtl/Clock_Enable_Generator.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/rtl/Binary_To_7Segment.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL 2008" -objects $file_obj

set file "$origin_dir/rtl/Counter_7Segment.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL 2008" -objects $file_obj

set file "$origin_dir/rtl/Blinking_Led.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL 2008" -objects $file_obj

set file "$origin_dir/rsc/VGA8.F16.mem"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "Memory File" -objects $file_obj

set file "$origin_dir/rsc/Zero.RAM.mem"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "Memory File" -objects $file_obj


# Set 'sources_1' fileset file properties for local files
# None

# Set 'sources_1' fileset properties
set obj [get_filesets sources_1]
set_property -name "dataflow_viewer_settings" -value "min_width=16" -objects $obj
set_property -name "top" -value "Text_Overlay_720p_Top" -objects $obj
set_property -name "top_auto_set" -value "0" -objects $obj

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 [file normalize "${origin_dir}/ip/clk_wiz_720p_0/clk_wiz_720p_0.xci"] \
]
add_files -norecurse -fileset $obj $files

# Set 'sources_1' fileset file properties for remote files
set file "$origin_dir/ip/clk_wiz_720p_0/clk_wiz_720p_0.xci"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}
set_property -name "used_in" -value "synthesis implementation" -objects $file_obj
set_property -name "used_in_simulation" -value "0" -objects $file_obj


# Set 'sources_1' fileset file properties for local files
# None

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 [file normalize "${origin_dir}/ip/clk_wiz_0/clk_wiz_0.xci"] \
]
add_files -norecurse -fileset $obj $files

# Set 'sources_1' fileset file properties for remote files
set file "$origin_dir/ip/clk_wiz_0/clk_wiz_0.xci"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}


# Set 'sources_1' fileset file properties for local files
# None

# Create 'constrs_1' fileset (if not found)
if {[string equal [get_filesets -quiet constrs_1] ""]} {
  create_fileset -constrset constrs_1
}

# Set 'constrs_1' fileset object
set obj [get_filesets constrs_1]

# Add/Import constrs file and set constrs file properties
set file "[file normalize "$origin_dir/cons/pynqz2_constraints.xdc"]"
set file_added [add_files -norecurse -fileset $obj [list $file]]
set file "$origin_dir/cons/pynqz2_constraints.xdc"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets constrs_1] [list "*$file"]]
set_property -name "file_type" -value "XDC" -objects $file_obj

# Set 'constrs_1' fileset properties
set obj [get_filesets constrs_1]

# Create 'constrs_blinking_led' fileset (if not found)
if {[string equal [get_filesets -quiet constrs_blinking_led] ""]} {
  create_fileset -constrset constrs_blinking_led
}

# Set 'constrs_blinking_led' fileset object
set obj [get_filesets constrs_blinking_led]

# Add/Import constrs file and set constrs file properties
set file "[file normalize "$origin_dir/cons/blinking_led_constraints.xdc"]"
set file_added [add_files -norecurse -fileset $obj [list $file]]
set file "$origin_dir/cons/blinking_led_constraints.xdc"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets constrs_blinking_led] [list "*$file"]]
set_property -name "file_type" -value "XDC" -objects $file_obj

# Set 'constrs_blinking_led' fileset properties
set obj [get_filesets constrs_blinking_led]
set_property -name "target_constrs_file" -value "[file normalize "$origin_dir/cons/blinking_led_constraints.xdc"]" -objects $obj
set_property -name "target_ucf" -value "[file normalize "$origin_dir/cons/blinking_led_constraints.xdc"]" -objects $obj

# Create 'constrs_counter_7segment' fileset (if not found)
if {[string equal [get_filesets -quiet constrs_counter_7segment] ""]} {
  create_fileset -constrset constrs_counter_7segment
}

# Set 'constrs_counter_7segment' fileset object
set obj [get_filesets constrs_counter_7segment]

# Add/Import constrs file and set constrs file properties
set file "[file normalize "$origin_dir/cons/counter_7segment_constraints.xdc"]"
set file_added [add_files -norecurse -fileset $obj [list $file]]
set file "$origin_dir/cons/counter_7segment_constraints.xdc"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets constrs_counter_7segment] [list "*$file"]]
set_property -name "file_type" -value "XDC" -objects $file_obj

# Set 'constrs_counter_7segment' fileset properties
set obj [get_filesets constrs_counter_7segment]
set_property -name "target_constrs_file" -value "[file normalize "$origin_dir/cons/counter_7segment_constraints.xdc"]" -objects $obj
set_property -name "target_ucf" -value "[file normalize "$origin_dir/cons/counter_7segment_constraints.xdc"]" -objects $obj

# Create 'constrs_hdmi' fileset (if not found)
if {[string equal [get_filesets -quiet constrs_hdmi] ""]} {
  create_fileset -constrset constrs_hdmi
}

# Set 'constrs_hdmi' fileset object
set obj [get_filesets constrs_hdmi]

# Add/Import constrs file and set constrs file properties
set file "[file normalize "$origin_dir/cons/hdmi_constraints.xdc"]"
set file_added [add_files -norecurse -fileset $obj [list $file]]
set file "$origin_dir/cons/hdmi_constraints.xdc"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets constrs_hdmi] [list "*$file"]]
set_property -name "file_type" -value "XDC" -objects $file_obj

# Set 'constrs_hdmi' fileset properties
set obj [get_filesets constrs_hdmi]
set_property -name "target_constrs_file" -value "[file normalize "$origin_dir/cons/hdmi_constraints.xdc"]" -objects $obj
set_property -name "target_ucf" -value "[file normalize "$origin_dir/cons/hdmi_constraints.xdc"]" -objects $obj

# Create 'constrs_hdmi_720p' fileset (if not found)
if {[string equal [get_filesets -quiet constrs_hdmi_720p] ""]} {
  create_fileset -constrset constrs_hdmi_720p
}

# Set 'constrs_hdmi_720p' fileset object
set obj [get_filesets constrs_hdmi_720p]

# Add/Import constrs file and set constrs file properties
set file "[file normalize "$origin_dir/cons/hdmi_720p_constraints.xdc"]"
set file_added [add_files -norecurse -fileset $obj [list $file]]
set file "$origin_dir/cons/hdmi_720p_constraints.xdc"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets constrs_hdmi_720p] [list "*$file"]]
set_property -name "file_type" -value "XDC" -objects $file_obj

# Set 'constrs_hdmi_720p' fileset properties
set obj [get_filesets constrs_hdmi_720p]

# Create 'constrs_test_pattern_720p' fileset (if not found)
if {[string equal [get_filesets -quiet constrs_test_pattern_720p] ""]} {
  create_fileset -constrset constrs_test_pattern_720p
}

# Set 'constrs_test_pattern_720p' fileset object
set obj [get_filesets constrs_test_pattern_720p]

# Add/Import constrs file and set constrs file properties
set file "[file normalize "$origin_dir/cons/test_pattern_constraints.xdc"]"
set file_added [add_files -norecurse -fileset $obj [list $file]]
set file "$origin_dir/cons/test_pattern_constraints.xdc"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets constrs_test_pattern_720p] [list "*$file"]]
set_property -name "file_type" -value "XDC" -objects $file_obj

# Set 'constrs_test_pattern_720p' fileset properties
set obj [get_filesets constrs_test_pattern_720p]

# Create 'constrs_pong_720p' fileset (if not found)
if {[string equal [get_filesets -quiet constrs_pong_720p] ""]} {
  create_fileset -constrset constrs_pong_720p
}

# Set 'constrs_pong_720p' fileset object
set obj [get_filesets constrs_pong_720p]

# Add/Import constrs file and set constrs file properties
set file "[file normalize "$origin_dir/cons/pong_720p_constraints.xdc"]"
set file_added [add_files -norecurse -fileset $obj [list $file]]
set file "$origin_dir/cons/pong_720p_constraints.xdc"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets constrs_pong_720p] [list "*$file"]]
set_property -name "file_type" -value "XDC" -objects $file_obj

# Set 'constrs_pong_720p' fileset properties
set obj [get_filesets constrs_pong_720p]
set_property -name "target_constrs_file" -value "[file normalize "$origin_dir/cons/pong_720p_constraints.xdc"]" -objects $obj
set_property -name "target_ucf" -value "[file normalize "$origin_dir/cons/pong_720p_constraints.xdc"]" -objects $obj

# Create 'constrs_text_overlay_720p' fileset (if not found)
if {[string equal [get_filesets -quiet constrs_text_overlay_720p] ""]} {
  create_fileset -constrset constrs_text_overlay_720p
}

# Set 'constrs_text_overlay_720p' fileset object
set obj [get_filesets constrs_text_overlay_720p]

# Add/Import constrs file and set constrs file properties
set file "[file normalize "$origin_dir/cons/text_overlay_720p.xdc"]"
set file_added [add_files -norecurse -fileset $obj [list $file]]
set file "$origin_dir/cons/text_overlay_720p.xdc"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets constrs_text_overlay_720p] [list "*$file"]]
set_property -name "file_type" -value "XDC" -objects $file_obj

# Set 'constrs_text_overlay_720p' fileset properties
set obj [get_filesets constrs_text_overlay_720p]

# Create 'sim_1' fileset (if not found)
if {[string equal [get_filesets -quiet sim_1] ""]} {
  create_fileset -simset sim_1
}

# Set 'sim_1' fileset object
set obj [get_filesets sim_1]
set files [list \
 [file normalize "${origin_dir}/tb/Text_Overlay_TB.sv"] \
 [file normalize "${origin_dir}/tb/Font_ROM_TB.sv"] \
 [file normalize "${origin_dir}/tb/TM_Choice_TB.sv"] \
 [file normalize "${origin_dir}/tb/ROM_TB.sv"] \
 [file normalize "${origin_dir}/tb/RAM_TB.sv"] \
 [file normalize "${origin_dir}/tb/Video_Signal_Generator_TB.sv"] \
 [file normalize "${origin_dir}/tb/FIFO_TB.sv"] \
 [file normalize "${origin_dir}/tb/Clock_TB.sv"] \
 [file normalize "${origin_dir}/tb/Counter_7Segment_TB.vhd"] \
 [file normalize "${origin_dir}/tb/Binary_To_7Segment_TB.vhd"] \
 [file normalize "${origin_dir}/tb/Blinking_Led_TB.vhd"] \
 [file normalize "${origin_dir}/rsc/VGA8_testing.F16.mem"] \
]
add_files -norecurse -fileset $obj $files

# Set 'sim_1' fileset file properties for remote files
set file "$origin_dir/tb/Text_Overlay_TB.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/tb/Font_ROM_TB.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/tb/TM_Choice_TB.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/tb/ROM_TB.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/tb/RAM_TB.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/tb/Video_Signal_Generator_TB.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/tb/FIFO_TB.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/tb/Clock_TB.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/tb/Counter_7Segment_TB.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/tb/Binary_To_7Segment_TB.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL 2008" -objects $file_obj

set file "$origin_dir/tb/Blinking_Led_TB.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL 2008" -objects $file_obj

set file "$origin_dir/rsc/VGA8_testing.F16.mem"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
set_property -name "file_type" -value "Memory File" -objects $file_obj


# Set 'sim_1' fileset file properties for local files
# None

# Set 'sim_1' fileset properties
set obj [get_filesets sim_1]
set_property -name "sim_wrapper_top" -value "1" -objects $obj
set_property -name "top" -value "Text_Overlay_TB" -objects $obj
set_property -name "top_auto_set" -value "0" -objects $obj
set_property -name "top_lib" -value "xil_defaultlib" -objects $obj

# Set 'utils_1' fileset object
set obj [get_filesets utils_1]
# Import local files from the original project
set files [list \
 [file normalize "${origin_dir}/Mini_Project_Starter/Mini_Project_Starter.srcs/utils_1/imports/synth_1/Pong_720p_Top.dcp" ]\
]
set imported_files ""
foreach f $files {
  lappend imported_files [import_files -fileset utils_1 $f]
}

# Set 'utils_1' fileset file properties for remote files
# None

# Set 'utils_1' fileset file properties for local files
set file "synth_1/Pong_720p_Top.dcp"
set file_obj [get_files -of_objects [get_filesets utils_1] [list "*$file"]]
set_property -name "netlist_only" -value "0" -objects $file_obj


# Set 'utils_1' fileset properties
set obj [get_filesets utils_1]

set idrFlowPropertiesConstraints ""
catch {
 set idrFlowPropertiesConstraints [get_param runs.disableIDRFlowPropertyConstraints]
 set_param runs.disableIDRFlowPropertyConstraints 1
}

# Create 'synth_1' run (if not found)
if {[string equal [get_runs -quiet synth_1] ""]} {
    create_run -name synth_1 -part xc7z020clg400-1 -flow {Vivado Synthesis 2024} -strategy "Vivado Synthesis Defaults" -report_strategy {No Reports} -constrset constrs_text_overlay_720p
} else {
  set_property strategy "Vivado Synthesis Defaults" [get_runs synth_1]
  set_property flow "Vivado Synthesis 2024" [get_runs synth_1]
}
set obj [get_runs synth_1]
set_property set_report_strategy_name 1 $obj
set_property report_strategy {Vivado Synthesis Default Reports} $obj
set_property set_report_strategy_name 0 $obj
# Create 'synth_1_synth_report_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs synth_1] synth_1_synth_report_utilization_0] "" ] } {
  create_report_config -report_name synth_1_synth_report_utilization_0 -report_type report_utilization:1.0 -steps synth_design -runs synth_1
}
set obj [get_report_configs -of_objects [get_runs synth_1] synth_1_synth_report_utilization_0]
if { $obj != "" } {

}
set obj [get_runs synth_1]
set_property -name "constrset" -value "constrs_text_overlay_720p" -objects $obj
set_property -name "incremental_checkpoint" -value "$proj_dir/${_xil_proj_name_}.srcs/utils_1/imports/synth_1/Pong_720p_Top.dcp" -objects $obj
set_property -name "auto_incremental_checkpoint" -value "1" -objects $obj
set_property -name "strategy" -value "Vivado Synthesis Defaults" -objects $obj

# set the current synth run
current_run -synthesis [get_runs synth_1]

# Create 'impl_1' run (if not found)
if {[string equal [get_runs -quiet impl_1] ""]} {
    create_run -name impl_1 -part xc7z020clg400-1 -flow {Vivado Implementation 2024} -strategy "Vivado Implementation Defaults" -report_strategy {No Reports} -constrset constrs_text_overlay_720p -parent_run synth_1
} else {
  set_property strategy "Vivado Implementation Defaults" [get_runs impl_1]
  set_property flow "Vivado Implementation 2024" [get_runs impl_1]
}
set obj [get_runs impl_1]
set_property set_report_strategy_name 1 $obj
set_property report_strategy {Vivado Implementation Default Reports} $obj
set_property set_report_strategy_name 0 $obj
# Create 'impl_1_init_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_init_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_init_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps init_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_init_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj
set_property -name "options.report_unconstrained" -value "1" -objects $obj

}
# Create 'impl_1_opt_report_drc_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_drc_0] "" ] } {
  create_report_config -report_name impl_1_opt_report_drc_0 -report_type report_drc:1.0 -steps opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_drc_0]
if { $obj != "" } {

}
# Create 'impl_1_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj
set_property -name "options.report_unconstrained" -value "1" -objects $obj

}
# Create 'impl_1_power_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_power_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_power_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps power_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_power_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj
set_property -name "options.report_unconstrained" -value "1" -objects $obj

}
# Create 'impl_1_place_report_io_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_io_0] "" ] } {
  create_report_config -report_name impl_1_place_report_io_0 -report_type report_io:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_io_0]
if { $obj != "" } {

}
# Create 'impl_1_place_report_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_utilization_0] "" ] } {
  create_report_config -report_name impl_1_place_report_utilization_0 -report_type report_utilization:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_utilization_0]
if { $obj != "" } {

}
# Create 'impl_1_place_report_control_sets_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_control_sets_0] "" ] } {
  create_report_config -report_name impl_1_place_report_control_sets_0 -report_type report_control_sets:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_control_sets_0]
if { $obj != "" } {
set_property -name "options.verbose" -value "1" -objects $obj

}
# Create 'impl_1_place_report_incremental_reuse_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_0] "" ] } {
  create_report_config -report_name impl_1_place_report_incremental_reuse_0 -report_type report_incremental_reuse:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj

}
# Create 'impl_1_place_report_incremental_reuse_1' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_1] "" ] } {
  create_report_config -report_name impl_1_place_report_incremental_reuse_1 -report_type report_incremental_reuse:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_1]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj

}
# Create 'impl_1_place_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_place_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj
set_property -name "options.report_unconstrained" -value "1" -objects $obj

}
# Create 'impl_1_post_place_power_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_post_place_power_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_post_place_power_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps post_place_power_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_post_place_power_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj
set_property -name "options.report_unconstrained" -value "1" -objects $obj

}
# Create 'impl_1_phys_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_phys_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_phys_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps phys_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_phys_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj
set_property -name "options.report_unconstrained" -value "1" -objects $obj

}
# Create 'impl_1_route_report_drc_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_drc_0] "" ] } {
  create_report_config -report_name impl_1_route_report_drc_0 -report_type report_drc:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_drc_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_methodology_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_methodology_0] "" ] } {
  create_report_config -report_name impl_1_route_report_methodology_0 -report_type report_methodology:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_methodology_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_power_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_power_0] "" ] } {
  create_report_config -report_name impl_1_route_report_power_0 -report_type report_power:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_power_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_route_status_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_route_status_0] "" ] } {
  create_report_config -report_name impl_1_route_report_route_status_0 -report_type report_route_status:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_route_status_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_route_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_timing_summary_0]
if { $obj != "" } {
set_property -name "options.max_paths" -value "10" -objects $obj
set_property -name "options.report_unconstrained" -value "1" -objects $obj

}
# Create 'impl_1_route_report_incremental_reuse_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_incremental_reuse_0] "" ] } {
  create_report_config -report_name impl_1_route_report_incremental_reuse_0 -report_type report_incremental_reuse:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_incremental_reuse_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_clock_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_clock_utilization_0] "" ] } {
  create_report_config -report_name impl_1_route_report_clock_utilization_0 -report_type report_clock_utilization:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_clock_utilization_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_bus_skew_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_bus_skew_0] "" ] } {
  create_report_config -report_name impl_1_route_report_bus_skew_0 -report_type report_bus_skew:1.1 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_bus_skew_0]
if { $obj != "" } {
set_property -name "options.warn_on_violation" -value "1" -objects $obj

}
# Create 'impl_1_post_route_phys_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_post_route_phys_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps post_route_phys_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "options.max_paths" -value "10" -objects $obj
set_property -name "options.report_unconstrained" -value "1" -objects $obj
set_property -name "options.warn_on_violation" -value "1" -objects $obj

}
# Create 'impl_1_post_route_phys_opt_report_bus_skew_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_bus_skew_0] "" ] } {
  create_report_config -report_name impl_1_post_route_phys_opt_report_bus_skew_0 -report_type report_bus_skew:1.1 -steps post_route_phys_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_bus_skew_0]
if { $obj != "" } {
set_property -name "options.warn_on_violation" -value "1" -objects $obj

}
set obj [get_runs impl_1]
set_property -name "constrset" -value "constrs_text_overlay_720p" -objects $obj
set_property -name "strategy" -value "Vivado Implementation Defaults" -objects $obj
set_property -name "steps.write_bitstream.args.readback_file" -value "0" -objects $obj
set_property -name "steps.write_bitstream.args.verbose" -value "0" -objects $obj

# set the current impl run
current_run -implementation [get_runs impl_1]
catch {
 if { $idrFlowPropertiesConstraints != {} } {
   set_param runs.disableIDRFlowPropertyConstraints $idrFlowPropertiesConstraints
 }
}

puts "INFO: Project created:${_xil_proj_name_}"
# Create 'drc_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "drc_1" ] ] ""]} {
create_dashboard_gadget -name {drc_1} -type drc
}
set obj [get_dashboard_gadgets [ list "drc_1" ] ]
set_property -name "reports" -value "impl_1#impl_1_route_report_drc_0" -objects $obj

# Create 'methodology_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "methodology_1" ] ] ""]} {
create_dashboard_gadget -name {methodology_1} -type methodology
}
set obj [get_dashboard_gadgets [ list "methodology_1" ] ]
set_property -name "reports" -value "impl_1#impl_1_route_report_methodology_0" -objects $obj

# Create 'power_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "power_1" ] ] ""]} {
create_dashboard_gadget -name {power_1} -type power
}
set obj [get_dashboard_gadgets [ list "power_1" ] ]
set_property -name "reports" -value "impl_1#impl_1_route_report_power_0" -objects $obj

# Create 'timing_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "timing_1" ] ] ""]} {
create_dashboard_gadget -name {timing_1} -type timing
}
set obj [get_dashboard_gadgets [ list "timing_1" ] ]
set_property -name "reports" -value "impl_1#impl_1_route_report_timing_summary_0" -objects $obj

# Create 'utilization_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "utilization_1" ] ] ""]} {
create_dashboard_gadget -name {utilization_1} -type utilization
}
set obj [get_dashboard_gadgets [ list "utilization_1" ] ]
set_property -name "reports" -value "synth_1#synth_1_synth_report_utilization_0" -objects $obj
set_property -name "run.step" -value "synth_design" -objects $obj
set_property -name "run.type" -value "synthesis" -objects $obj

# Create 'utilization_2' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "utilization_2" ] ] ""]} {
create_dashboard_gadget -name {utilization_2} -type utilization
}
set obj [get_dashboard_gadgets [ list "utilization_2" ] ]
set_property -name "reports" -value "impl_1#impl_1_place_report_utilization_0" -objects $obj

move_dashboard_gadget -name {utilization_1} -row 0 -col 0
move_dashboard_gadget -name {power_1} -row 1 -col 0
move_dashboard_gadget -name {drc_1} -row 2 -col 0
move_dashboard_gadget -name {timing_1} -row 0 -col 1
move_dashboard_gadget -name {utilization_2} -row 1 -col 1
move_dashboard_gadget -name {methodology_1} -row 2 -col 1
